- name: set variables
  set_fact:
    shell_user_name: "{{ ansible_env.USER }}"

- name: change default shell
  become: yes
  user:
    name: "{{ shell_user_name }}"
    shell: /home/linuxbrew/.linuxbrew/bin/zsh
