
- name: install zsh with homebrew
  homebrew:
    name: zsh

- name: check zinit
  stat:
    path: "{{ home_dir }}/.zinit/bin"
  register: zinit_installed

- name: make zinit directory
  file:
    path: "{{ home_dir }}/.zinit"
    state: directory

- name: get zinit
  git:
    repo: https://github.com/zdharma/zinit.git
    dest: "{{ home_dir }}/.zinit/bin"
  when: not zinit_installed.stat.exists

- name: .zinit chmod 755
  file:
    dest: "{{ home_dir }}/.zinit"
    mode: 0755
    recurse: True

- name: check ansible managed block .zshrc
  shell: grep "ANSIBLE MANAGED BLOCK" -- {{ home_dir }}/.zshrc
  register: exists_ansible_managed_block
  changed_when: False
  ignore_errors: yes

- name: remove default .zshrc
  file:
    path: "{{ home_dir }}/.zshrc"
    state: absent
  when: is_linux and exists_ansible_managed_block.rc != 0

- name: create .zshrc
  file:
    path: "{{ home_dir }}/.zshrc"
    state: touch
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"

- name: add .zshrc content
  blockinfile:
    dest: "{{ home_dir }}/.zshrc"
    content: |
      {{ lookup('file', '.zshrc') }}

- name: check ansible managed block .zprofile
  shell: grep "ANSIBLE MANAGED BLOCK" -- {{ home_dir }}/.zprofile
  register: exists_ansible_managed_block
  changed_when: False
  ignore_errors: yes

- name: remove default .zprofile
  file:
    path: "{{ home_dir }}/.zprofile"
    state: absent
  when: is_linux and exists_ansible_managed_block.rc != 0

- name: create .zprofile
  file:
    path: "{{ home_dir }}/.zprofile"
    state: touch
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"

- name: add .zprofile content
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK zsh role"
    dest: "{{ home_dir }}/.zprofile"
    content: |
      {{ lookup('file', '.zprofile') }}

- name: clone zsh-capture-completion
  git:
    repo: https://github.com/Valodim/zsh-capture-completion.git
    dest: "{{ app_dir }}/zsh-capture-completion"

- name: copy capture.zsh
  copy:
    src: "{{ app_dir }}/zsh-capture-completion/capture.zsh"
    dest: "{{ home_dir }}/.local/bin/capture.zsh"

- name: capture.zsh chmod 755
  file:
    dest: "{{ home_dir }}/.local/bin/capture.zsh"
    mode: 0755
