
- name: install zsh with homebrew
  homebrew:
    name: zsh
  when: is_macos

- name: make zsh directory
  file:
    path: "{{ app_dir }}/zsh"
    state: directory
  when: is_linux

- name: check zsh download
  stat:
    path: "{{ app_dir }}/zsh.tar.xz"
  register: zsh_downloaded
  when: is_linux

- name: download zsh
  get_url:
    url: https://sourceforge.net/projects/zsh/files/zsh/5.6.2/zsh-5.6.2.tar.xz/download
    dest: "{{ app_dir }}/zsh.tar.xz"
  when: is_linux and not zsh_downloaded.stat.exists

- name: check zsh binary
  stat:
    path: "/usr/local/bin/zsh"
  register: zsh_binary
  when: is_linux

- name: unarchive zsh
  unarchive:
    src: "{{ app_dir }}/zsh.tar.xz"
    dest: "{{ app_dir }}/zsh"
    extra_opts: [--strip-components=1]
  when: is_linux and not zsh_downloaded.stat.exists

- name: config
  shell: |
    ./configure \
      --enable-multibyte \
  args:
    chdir: "{{ app_dir }}/zsh"
  when: is_linux and not zsh_binary.stat.exists

- name: build
  make:
    chdir: "{{ app_dir }}/zsh"
  when: is_linux and not zsh_binary.stat.exists

- name: install
  make:
    target: install
    chdir: "{{ app_dir }}/zsh"
  when: is_linux and not zsh_binary.stat.exists
  become: yes

- name: check zinit
  stat:
    path: "{{ home_dir }}/.zinit/bin"
  register: zinit_installed

- name: make zinit directory
  file:
    path: "{{ app_dir }}/.zinit"
    state: directory

- name: get zinit
  git:
    repo: https://github.com/zdharma/zinit.git
    dest: "{{ home_dir }}/.zinit/bin"
  when: not zinit_installed.stat.exists

- name: .zinit chmod 755
  file:
    dest: "{{ home_dir }}/.zinit"
    mode: 0755
    recurse: True

- name: check ansible managed block .zshrc
  shell: grep "ANSIBLE MANAGED BLOCK" -- {{ home_dir }}/.zshrc
  register: exists_ansible_managed_block
  changed_when: False
  ignore_errors: yes

- name: remove default .zshrc
  file:
    path: "{{ home_dir }}/.zshrc"
    state: absent
  when: is_linux and exists_ansible_managed_block.rc != 0

- name: create .zshrc
  file:
    path: "{{ home_dir }}/.zshrc"
    state: touch
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"

- name: add .zshrc content
  blockinfile:
    dest: "{{ home_dir }}/.zshrc"
    content: |
      {{ lookup('file', '.zshrc') }}

- name: check ansible managed block .zprofile
  shell: grep "ANSIBLE MANAGED BLOCK" -- {{ home_dir }}/.zprofile
  register: exists_ansible_managed_block
  changed_when: False
  ignore_errors: yes

- name: remove default .zprofile
  file:
    path: "{{ home_dir }}/.zprofile"
    state: absent
  when: is_linux and exists_ansible_managed_block.rc != 0

- name: create .zprofile
  file:
    path: "{{ home_dir }}/.zprofile"
    state: touch
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"

- name: add .zprofile content
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK zsh role"
    dest: "{{ home_dir }}/.zprofile"
    content: |
      {{ lookup('file', '.zprofile') }}
