# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.3"

  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.synced_folder "C:/Users", "/c/Users", type: nil
  config.vm.synced_folder ".", "/vagrant", type: nil
  config.vm.synced_folder "~", "/hostusr", type: nil
  config.vm.box_check_update = false
  config.ssh.guest_port = 2222

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
  end

  config.vm.provision "shell", path: './provision/first_root.sh'
  config.vm.provision "shell", privileged: false, path: './provision/first.sh'
  config.vm.provision "shell", run: 'always', path: './provision/always_root.sh'
  config.vm.provision "shell", privileged: false, run: 'always', path: './provision/always.sh'
end
