- name: set variables
  set_fact:
    wslu_dir: "{{ app_dir }}/wslu"
  when: is_ubuntu

- name: git clone wslu
  git:
    repo: https://github.com/wslutilities/wslu.git
    dest: "{{ wslu_dir }}"
  when: is_ubuntu

- name: wslu make all
  make:
    target: all
    chdir: "{{ wslu_dir }}"
    params:
      PREFIX: ""
  when: is_ubuntu

- name: wslu make install
  make:
    target: install
    chdir: "{{ wslu_dir }}"
    params:
      PREFIX: ""
      DESTDIR: "{{ home_dir }}/.local/wslu"
  when: is_ubuntu

- name: add .bash_profile content for wslu
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK wslu"
    dest: "{{ home_dir }}/.bash_profile"
    content: |
      export WSLVIEW_DEFAULT_ENGINE=powershell
      export PATH=$HOME/.local/wslu/bin:$PATH
  when: is_ubuntu
