require("searcho").setup_keymaps(function(vim)
  vim.keymap.set("c", "<Tab>", [[<C-g>]], { buf = 0 })
  vim.keymap.set("c", "<S-Tab>", [[<C-t>]], { buf = 0 })
  vim.keymap.set("c", "<Space>", [[<CR>]], { buf = 0 })
  vim.keymap.set("c", "<C-Space>", [[<Space>]], { buf = 0 })
end)
