
- name: check ansible managed block .bashrc
  shell: grep "ANSIBLE MANAGED BLOCK" -- {{ home_dir }}/.bashrc
  register: exists_ansible_managed_block
  when: is_linux
  changed_when: False
  ignore_errors: yes

- name: remove default .bashrc
  file:
    path: "{{ home_dir }}/.bashrc"
    state: absent
  when: is_linux and exists_ansible_managed_block.rc != 0

- name: check ansible managed block .bash_profile
  shell: grep "ANSIBLE MANAGED BLOCK" -- {{ home_dir }}/.bash_profile
  register: exists_ansible_managed_block
  when: is_linux
  changed_when: False
  ignore_errors: yes

- name: remove default .bash_profile
  file:
    path: "{{ home_dir }}/.bash_profile"
    state: absent
  when: is_linux and exists_ansible_managed_block.rc != 0

- name: create .bashrc
  file:
    path: "{{ home_dir }}/.bashrc"
    state: touch
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"

- name: create .local/.bashrc
  file:
    path: "{{ home_dir }}/.local/.bashrc"
    state: touch
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"

- name: create .bash_profile
  file:
    path: "{{ home_dir }}/.bash_profile"
    state: touch
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"

- name: create .local/.bash_profile
  file:
    path: "{{ home_dir }}/.local/.bash_profile"
    state: touch
  register: touch_log
  changed_when: touch_log.diff.before.state != "file"

- name: add .bashrc content
  blockinfile:
    dest: "{{ home_dir }}/.bashrc"
    content: |
      {{ lookup('file', '.bashrc') }}

- name: add .bashrc content on mac
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK bash on mac"
    dest: "{{ home_dir }}/.bashrc"
    content: |
      alias anc='cd ~/dotfiles/ansible;ansible-playbook playbooks/mac.yml'
      alias anct='cd ~/dotfiles/ansible;ansible-playbook playbooks/mac.yml --tags'
      alias psa='ps -aux'
  when: is_macos

- name: add .bashrc content on centos
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK bash on centos"
    dest: "{{ home_dir }}/.bashrc"
    content: |
      alias anc='cd ~/dotfiles/ansible;ansible-playbook playbooks/centos7.yml'
      alias anct='cd ~/dotfiles/ansible;ansible-playbook playbooks/centos7.yml --tags'
  when: is_centos

- name: add .bashrc content on ubuntu
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK bash on centos"
    dest: "{{ home_dir }}/.bashrc"
    content: |
      alias anc='cd ~/dotfiles/ansible;ansible-playbook playbooks/ubuntu.yml'
      alias anct='cd ~/dotfiles/ansible;ansible-playbook playbooks/ubuntu.yml --tags'
  when: is_ubuntu

- name: add .bash_profile content
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK bash role"
    dest: "{{ home_dir }}/.bash_profile"
    content: |
      {{ lookup('file', '.bash_profile') }}

- name: copy .inputrc
  copy:
    src: .inputrc
    dest: "{{ home_dir }}/.inputrc"
