
- name: check .gitconfig
  stat:
    path: "{{ home_dir }}/.gitconfig"
  register: gitconfig_file

- name: copy .gitconfig
  copy:
    src: "{{ home_dir }}/dotfiles/git/.gitconfig"
    dest: "{{ home_dir }}/.gitconfig"
  when: not gitconfig_file.stat.exists

- name: input git user name
  pause:
    prompt: "input git user name"
  register: git_user_name
  when: not gitconfig_file.stat.exists

- name: input git user email
  pause:
    prompt: "input git user email"
  register: git_user_email
  when: not gitconfig_file.stat.exists

- name: set git user name
  git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name.user_input }}"
  when: not gitconfig_file.stat.exists

- name: set git user email
  git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email.user_input }}"
  when: not gitconfig_file.stat.exists
