
- name: install xinetd with yum
  yum:
    name: xinetd
  become: yes
  when: is_centos

- name: install lsyncd with yum
  yum:
    name: lsyncd
    enablerepo: epel
  become: yes
  when: is_centos

- name: start xinetd service
  systemd:
    name: xinetd
    state: started
  become: yes
  when: is_centos

- name: enable xinetd service
  systemd:
    name: xinetd
    enabled: yes
  become: yes
  when: is_centos

- name: copy lsyncd.conf
  copy:
    src: lsyncd.conf
    dest: "/etc/lsyncd.conf"
  become: yes
  when: is_centos

- name: copy rsync_exclude_list
  copy:
    src: rsync_exclude_list
    dest: "/etc/rsync_exclude_list"
  become: yes
  when: is_centos

- name: start lsyncd service
  systemd:
    name: lsyncd
    state: started
  become: yes
  when: is_centos

- name: enable lsyncd service
  systemd:
    name: lsyncd
    enabled: yes
  become: yes
  when: is_centos
