- hosts: 'local'
  vars_files:
    - '{{ inventory_dir | dirname }}/vars/{{ ansible_os_family }}.yml'
  roles:
    - { role: 'vim', tags: 'vim' }
    - { role: 'firefox', tags: 'firefox' }
    - { role: 'tmux', tags: 'tmux' }
    - { role: 'mysql', tags: 'mysql' }
    - { role: 'ruby', tags: 'ruby' }
    - { role: 'rust', tags: 'rust' }
  tasks:
    - name: install with homebrew_cask
      homebrew_cask: name={{ item }}
      with_items:
        - xquartz
        - inkscape
        - dropbox
        - blender
        - gimp
        - flux
