- hosts: 'local'
  vars_files:
    - '{{ inventory_dir | dirname }}/vars/{{ ansible_os_family }}.yml'
  tasks:
    - name: install with homebrew_cask
      homebrew_cask: name={{ item }}
      with_items:
        - xquartz
        - inkscape
        - dropbox
        - blender
        - gimp
        - flux
