- name: make gcloud directory
  file:
    path: "{{ app_dir }}/gcloud"
    state: directory

- name: download gcloud
  get_url:
    url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-444.0.0-linux-x86_64.tar.gz
    dest: "{{ app_dir }}/gcloud.tar.gz"
  when: is_ubuntu

- name: unarchive gcloud
  unarchive:
    src: "{{ app_dir }}/gcloud.tar.gz"
    dest: "{{ app_dir }}/gcloud"

- name: add .zshrc content
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK gcloud role"
    dest: "{{ home_dir }}/.zshrc"
    content: |
      if [ -f '{{ home_dir }}/app/gcloud/google-cloud-sdk/path.zsh.inc' ]; then . '{{ home_dir }}/app/gcloud/google-cloud-sdk/path.zsh.inc'; fi

# manual
# cd ~/app/gcloud/google-cloud-sdk; ./install.sh
