call curstr#custom#filetype_source('php', ['tag', 'blade'])
call curstr#custom#filetype_alias('blade', 'php')
call curstr#custom#filetype_source('vim', ['file', 'vim/runtime', 'vim/function', 'vim/help'])
call curstr#custom#filetype_alias('toml', 'vim')
call curstr#custom#filetype_source('python', ['vim/function'])
call curstr#custom#source_alias('openable', ['file', 'directory'])
call curstr#custom#filetype_source('_', ['openable', 'vim/function'])
call curstr#custom#execute_option('use-cache', v:false)
