
- name: set variables
  set_fact:
    vim_dir: "{{ app_dir }}/vim"

- name: install vim with homebrew
  homebrew:
    name: vim
    install_options: with-python3
  when: is_macos

- name: check vim version
  shell: 'vim --version | head -n 1 | grep "VIM - Vi IMproved 8.1"'
  register: vim8_exists
  ignore_errors: yes
  changed_when: False

- name: check vim clone
  stat:
    path: "{{ vim_dir }}"
  register: vim_cloned
  when: is_linux

- name: git clone
  git:
    repo: https://github.com/vim/vim.git
    dest: "{{ vim_dir }}"
    version: master
  when: is_linux and not vim_cloned.stat.exists

- name: clean
  make:
    target: distclean
    chdir: "{{ vim_dir }}"
  when: is_linux and not vim8_exists.stdout

- name: clean
  make:
    target: clean
    chdir: "{{ vim_dir }}"
  when: is_linux and not vim8_exists.stdout

- name: edit cflags for gdb
  lineinfile:
    dest: "{{ vim_dir }}/src/Makefile"
    state: present
    regexp: "^#CFLAGS = -g$"
    line: "CFLAGS = -ggdb3"
  when: is_linux and not vim8_exists.stdout

- name: edit strip for gdb
  lineinfile:
    dest: "{{ vim_dir }}/src/Makefile"
    state: present
    regexp: "^#STRIP = /bin/true$"
    line: "STRIP = /bin/true"
  when: is_linux and not vim8_exists.stdout

- name: config
  shell: |
    ./configure \
      --with-features=huge \
      --enable-python3interp=dynamic \
      --with-python3-config-dir=/usr/lib64/python3.6/config-3.6m-x86_64-linux-gnu
  args:
    chdir: "{{ vim_dir }}/src"
  when: is_centos and not vim8_exists.stdout

- name: config
  shell: |
    ./configure \
      --with-features=huge \
      --enable-python3interp=dynamic \
      --with-python3-config-dir=/usr/lib64/python3.6/config-3.6m-x86_64-linux-gnu
  args:
    chdir: "{{ vim_dir }}/src"
  when: is_ubuntu and not vim8_exists.stdout

- name: build
  make:
    chdir: "{{ vim_dir }}/src"
  when: is_linux and not vim8_exists.stdout

- name: install
  make:
    target: install
    chdir: "{{ vim_dir }}/src"
  when: is_linux and not vim8_exists.stdout
  become: yes
