- hosts: all
  roles:
    - 'bash'
    - 'workspace'
    - 'golang'
    - 'dotfiles'
    - 'tools'
    - 'python'
    - 'php'
    - 'node'
    - 'docker'
    - 'neovim'
    - 'git'
  vars_files:
    - './vars/RedHat.yml'
