
- name: install terminal with homebrew_cask
  homebrew_cask: name={{ item }}
  with_items:
    - iterm2
    - alacritty
  when: is_macos

- name: mkdir .config/alacritty
  file:
    path: "{{ home_dir }}/.config/alacritty"
    state: directory
  when: is_macos

- name: copy alacritty.yml
  copy:
    src: alacritty.yml
    dest: "{{ home_dir }}/.config/alacritty/alacritty.yml"
  when: is_macos

- homebrew: name=tmux
  when: is_macos
