- name: install with homebrew
  homebrew:
    name:
      - luarocks
      - luajit
      - lua-language-server
      - stylua

- name: install vusted
  shell: luarocks --lua-version=5.1 install vusted
